blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^python/$', views.python_list, name='python_list'),
    url(r'^linux/$', views.linux_list, name='linux_list'),
    url(r'^other/$', views.other_list, name='other_list'),
    url(r'^essay/$', views.essay_list, name='essay_list'),
    url(r'^message/$', views.message, name='message'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^push/$', views.push, name='push'),
    url(r'^add_tags/$', views.add_tags, name='add_tags'),
    url(r'^del_comment/$', views.del_comment, name='del_comment'),
    url(r'^del_reply/$', views.del_reply, name='del_reply'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User


class Comment(models.Model):

    text = models.TextField()
    delete = models.SmallIntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]


class Reply(models.Model):
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    delete = models.SmallIntegerField(default=0)
    reply_type = models.SmallIntegerField(default=0)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    comment_reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.text[0:20]

templates/search/search.html
{% extends 'base_list.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <!--<article class="post post-{{ result.object.pk }}">-->
                <!--<header class="entry-header">-->
                    <!--<h1 class="entry-title">-->
                        <!--<a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>-->
                    <!--</h1>-->
                    <!--<div class="entry-meta">-->
                    <!--<span class="post-category">-->
                        <!--<a href="{% url 'blog:category' result.object.category.pk %}">-->
                            <!--{{ result.object.category.name }}</a></span>-->
                        <!--<span class="post-date"><a href="#">-->
                            <!--<time class="entry-date" datetime="{{ result.object.created_time }}">-->
                                <!--{{ result.object.created_time }}</time></a></span>-->
                        <!--<span class="post-author"><a href="#">{{ result.object.author }}</a></span>-->
                        <!--<span class="comments-link">-->
                        <!--<a href="{{ result.object.get_absolute_url }}#comment-area">-->
                            <!--{{ result.object.comment_set.count }} 评论</a></span>-->
                        <!--<span class="views-count"><a-->
                                <!--href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>-->
                    <!--</div>-->
                <!--</header>-->
                <!--<div class="entry-content clearfix">-->
                    <!--<p>{% highlight result.object.body with query %}</p>-->
                    <!--<div class="read-more cl-effect-14">-->
                        <!--<a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span-->
                                <!--class="meta-nav">→</span></a>-->
                    <!--</div>-->
                <!--</div>-->
            <!--</article>-->

            <div class="card article_list border border-success">
                <div class="card-body">
                    <h4 class="card-link article_title" style="text-align: center">
                        <a class="card-link" href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                    </h4>
                    <div class="article_info alert alert-success" style="text-align: center;padding: 5px 0px;">
                        <span class="mx-auto" style="padding: 0px 5px;"><a href="#">{{ result.object.category.name }}</a></span>
                        <span class="" style="padding: 0px 5px;"><a href="#"><time datetime="{{ post.created_time }}">{{ result.object.created_time | timesince }}前</time></a></span>
                        <!--<span class="" style="padding: 0px 5px;"><a href="#">{{ post.author }}</a></span>-->
                        <span class="" style="padding: 0px 5px;"><a href="#">{{ result.object.comment_set.count }} 评论</a></span>
                        <span><a href="#" style="padding: 0px 5px;">{{ result.object.views }} 阅读</a></span>
                    </div>
                    <div class="clearfix">
                        <p>{{% highlight result.object.body with query | safe %}...</p>
                        <div style="text-align: center">
                            <a href="{{ result.object.get_absolute_url }}" class="" style="color: #85b9ff;">继续阅读 <span class="">→</span></a>
                        </div>
                    </div>
                </div>
            </div>

        {% empty %}
            <div class="no-post">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}
{% endblock main %}