blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^python/$', views.python_list, name='python_list'),
    url(r'^linux/$', views.linux_list, name='linux_list'),
    url(r'^other/$', views.other_list, name='other_list'),
    url(r'^essay/$', views.essay_list, name='essay_list'),
    url(r'^message/$', views.message, name='message'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^push/$', views.push, name='push'),
    url(r'^add_tags/$', views.add_tags, name='add_tags'),
    url(r'^del_comment/$', views.del_comment, name='del_comment'),
    url(r'^del_reply/$', views.del_reply, name='del_reply'),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
    url(r'^reply/post/(?P<post_pk>[0-9]+)/$', views.post_reply, name='post_reply'),
]

blog/models.py
import markdown
from django.utils.html import strip_tags
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)  # 分类名

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)  # 标签名

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)  # 文章标题
    body = models.TextField()  # 文章正文
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # 文章分类
    tags = models.ManyToManyField(Tag, blank=True)  # 文章标签
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 文章作者
    views = models.PositiveIntegerField(default=0)  # 阅读量

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = '    '+strip_tags(md.convert(self.body))[:80]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']

comments/models.py
from django.db import models
from django.contrib.auth.models import User


class Comment(models.Model):

    text = models.TextField()
    delete = models.SmallIntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]


class Reply(models.Model):
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    delete = models.SmallIntegerField(default=0)
    reply_type = models.SmallIntegerField(default=0)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    comment_reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.text[0:20]

blog/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from comments.forms import CommentForm
from comments.models import Comment, Reply
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.contrib.auth.decorators import login_required
from django.db.utils import IntegrityError
from .form import PostForm
from .models import Post, Category, Tag
import markdown
import json
import datetime


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data( **kwargs)
        context.update({
            'htitle': "首页-梦flying的博客"
        })
        return context

    # 分页

    # def get_context_data(self, **kwargs):
    #     """
    #     在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
    #     例如 render(request, 'blog/index.html', context={'post_list': post_list})，
    #     这里传递了一个 {'post_list': post_list} 字典给模板。
    #     在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
    #     所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
    #     """
    #
    #     # 首先获得父类生成的传递给模板的字典。
    #     context = super().get_context_data(**kwargs)
    #
    #     # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
    #     # paginator 是 Paginator 的一个实例，
    #     # page_obj 是 Page 的一个实例，
    #     # is_paginated 是一个布尔变量，用于指示是否已分页。
    #     # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
    #     # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
    #     # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
    #     paginator = context.get('paginator')
    #     page = context.get('page_obj')
    #     is_paginated = context.get('is_paginated')
    #
    #     # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
    #     pagination_data = self.pagination_data(paginator, page, is_paginated)
    #
    #     # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
    #     context.update(pagination_data)
    #
    #     # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
    #     # 注意此时 context 字典中已有了显示分页导航条所需的数据。
    #     return context

    # def pagination_data(self, paginator, page, is_paginated):
    #     if not is_paginated:
    #         # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
    #         return {}
    #
    #     # 当前页左边连续的页码号，初始值为空
    #     left = []
    #
    #     # 当前页右边连续的页码号，初始值为空
    #     right = []
    #
    #     # 标示第 1 页页码后是否需要显示省略号
    #     left_has_more = False
    #
    #     # 标示最后一页页码前是否需要显示省略号
    #     right_has_more = False
    #
    #     # 标示是否需要显示第 1 页的页码号。
    #     # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    #     # 其它情况下第一页的页码是始终需要显示的。
    #     # 初始值为 False
    #     first = False
    #
    #     # 标示是否需要显示最后一页的页码号。
    #     # 需要此指示变量的理由和上面相同。
    #     last = False
    #
    #     # 获得用户当前请求的页码号
    #     page_number = page.number
    #
    #     # 获得分页后的总页数
    #     total_pages = paginator.num_pages
    #
    #     # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    #     page_range = paginator.page_range
    #
    #     if page_number == 1:
    #         # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
    #         # 此时只要获取当前页右边的连续页码号，
    #         # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
    #         # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
    #         right = page_range[page_number:page_number + 2]
    #
    #         # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
    #         # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
    #         if right[-1] < total_pages - 1:
    #             right_has_more = True
    #
    #         # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
    #         # 所以需要显示最后一页的页码号，通过 last 来指示
    #         if right[-1] < total_pages:
    #             last = True
    #
    #     elif page_number == total_pages:
    #         # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
    #         # 此时只要获取当前页左边的连续页码号。
    #         # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
    #         # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
    #         left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
    #
    #         # 如果最左边的页码号比第 2 页页码号还大，
    #         # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
    #         if left[0] > 2:
    #             left_has_more = True
    #
    #         # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
    #         # 所以需要显示第一页的页码号，通过 first 来指示
    #         if left[0] > 1:
    #             first = True
    #     else:
    #         # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
    #         # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
    #         left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
    #         right = page_range[page_number:page_number + 2]
    #
    #         # 是否需要显示最后一页和最后一页前的省略号
    #         if right[-1] < total_pages - 1:
    #             right_has_more = True
    #         if right[-1] < total_pages:
    #             last = True
    #
    #         # 是否需要显示第 1 页和第 1 页后的省略号
    #         if left[0] > 2:
    #             left_has_more = True
    #         if left[0] > 1:
    #             first = True
    #
    #     data = {
    #         'left': left,
    #         'right': right,
    #         'left_has_more': left_has_more,
    #         'right_has_more': right_has_more,
    #         'first': first,
    #         'last': last,
    #     }
    #
    #     return data


def python_list(request):
    category = Category.objects.get(name='Python')
    post = Post.objects.filter(category_id=category)
    context = {
        'python_list': post,
        'htitle': "Python-梦flying的博客",
    }
    return render(request, 'blog/python.html', context=context)


def linux_list(request):
    category = Category.objects.get(name='Linux')
    post = Post.objects.filter(category_id=category)
    context = {
        'linux_list': post,
        'htitle': "Linux-梦flying的博客",
        'nav': 2,
    }
    return render(request, 'blog/Linux.html', context=context)


def other_list(request):
    category = Category.objects.get(name='Other')
    post = Post.objects.filter(category_id=category)
    context = {
        'other_list': post,
        'htitle': "其他技术文章-梦flying的博客",
        'nav': 3,
    }
    return render(request, 'blog/other.html', context=context)


def essay_list(request):
    category = Category.objects.get(name='Essay')
    post = Post.objects.filter(category_id=category)
    context = {
        'essay_list': post,
        'htitle': "随笔-梦flying的博客",
    }
    return render(request, 'blog/essay.html', context=context)


def message(request):
    context = {
        'htitle': "与我联系-梦flying的博客",
    }
    return render(request, 'blog/message.html', context=context)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class ArchivesView(IndexView):
    def get_queryset(self):
        # year = get_object_or_404(Category, pk=self.kwargs.get('year'))
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
    
    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            TocExtension(slugify=slugify, baselevel=2),
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        # if len(post.toc) == 0:
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


@login_required()
def push(request):
    if request.method == 'POST'and request.user.is_staff:
        form = PostForm(request.POST)
        if form.is_valid():
            tags = request.POST.getlist('tags[]')
            # return HttpResponse(tags)
            post = form.save(commit=False)
            post.author = request.user
            post.created_time = datetime.datetime.now()
            post.modified_time = datetime.datetime.now()
            post.save()
            post.tags.set(tags)
            return redirect('/')
    else:
        form = PostForm()
        context = {
            'form': form,
        }
    return render(request, 'blog/push.html', context=context)


@login_required()
def add_tags(request):
    if request.method == 'POST' and request.user.is_staff:
        tags = request.POST.get('tags', '')
        tags_list = tags.split()
        response = {}
        for tag in tags_list:
            try:
                tag_obj = Tag()
                tag_obj.name = tag
                tag_obj.save()
                response[tag] = "添加成功！"
            except IntegrityError:

templates/blog/detail.html
{% extends 'base_list.html' %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block head_child %}
<script>
    $(function () {
        $("img").addClass("img-fluid");
    });
    // tinyMCE.init({
    //         'mode':'textareas',
    //         'theme':'modern',
    //     });
</script>
{% endblock head_child %}


{% block main %}
<article class="post post-{{post.pk}}"  style="color: #444;background-color: white;padding: 20px;margin-top: 10px;">
    <header class="entry-header">
        <h2 class="text-center" style="margin: 10px 0px;">{{post.title}}</h2>
        <div class="entry-meta" style="color: #00a67c;text-align: center; padding: 5px 0px;">
            <!--<span>{{post.category.name}}</span>-->
            <span style="padding: 0px 8px;">
                <time class="entry-date" datetime="{{post.created_time}}">
                    <i class="fa fa-clock-o" style="padding-right: 2px;"></i>{{post.created_time | timesince}} 前
                </time>
            </span>
            <span style="padding: 0px 8px;" style="padding-right: 2px;">
                <i class="fa fa-user" style="padding-right: 2px;"></i>{{post.author}}
            </span>
            <span style="padding: 0px 8px;">
                <i class="fa fa-comment" style="padding-right: 2px;"></i>{{ post.comment_set.count }} 评论
            </span>
            <span style="padding: 0px 8px;">
                <i class="fa fa-eye" style="padding-right: 2px;"></i>{{post.views}} 阅读
            </span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{post.body|safe}}
    </div>
</article>
<div class="form-group">
    <hr>
    <h4>发表评论</h4>
    <form action="{% url 'comments:post_comment' post.pk %}?#comment_list" method="post" class="comment-form">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-12">
          <label for="{{ form.text.id_for_label }}">评论：</label>
          {% bootstrap_field form.text show_label=False size="sm"  placeholder='请输入联系内容' %}
          {{ form.text.errors }}
          {% buttons submit='发表' reset="取消" %}{% endbuttons %}
        </div>
      </div>    <!-- row -->
    </form>
    <div class="comment-list-panel" id="comment_list">
        <h4>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h4>
        <div>
            <ul class="comment_list list-unstyled">
                {% for comment in comment_list %}
                <hr>
                <li class="comment-item clearfix" id="comment-{{ comment.id }}">
                    <div class="panel panel-default ">
                        <div class="panel-body comment_body">
                            <span class="nickname" style="color: #00a67c;">{{ comment.user.username }}</span>
                            <time class="submit-date">{{ comment.created_time }}</time>
                            <div class="text comment_text">
                                <div class="comment" style="display: block;">
                                    <span style="padding: 5px 10px;">{{ comment.text|safe }}</span>
                                    <span class="reply_comment">回复</span>
                                    {% if user.is_staff %}
                                    <span class="reply_comment_del" data-csrf="{{ csrf_token }}" data-comment-id="{{ comment.id }}">删除</span>
                                    {% endif %}
                                </div>
                                <div class="reply_form col-lg-10" style="display: none;">
                                    <form role="form" method="post" action="{% url 'comments:post_reply' post.pk %}?#comment-{{ comment.id }}">
                                        {% csrf_token %}
                                        <input type="hidden" name="reply_type" value="0">
                                        <input type="hidden" name="comment" value="{{comment.id}}">
                                        <input type="hidden" name="comment_reply" value="">
                                        <div class="form-group">
                                            <textarea class="form-control" rows="2" name="text"  placeholder="回复{{comment.user.username}}："></textarea>
                                        </div>
                                        {% for field in reply_form %}
                                            {{ field.errors }}
                                        {% endfor %}
                                        <div class="form-group">
                                            <div class="btn-group pull-right">
                                                <button type="button" class="btn btn-default reply_form_close">关闭</button>
                                                <button type="submit" class="btn btn-success">发表</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div  class="reply_list" style="padding-left: 10px;">
                                <ul class="list-unstyled">
                                {% for reply in comment.reply_set.all %}
                                    <li class="reply_li">
                                        <div class="reply">
                                            <div class="clearfix col-lg-12" style="padding: 5px 5px;display: block;">
                                                <span style="color: #00a67c;">{{reply.user.username}}</span>
                                                <span class="fa fa-mail-forward"></span>

                                                {% if reply.comment_reply %}
                                                <span style="color: #00a67c;">{{reply.comment_reply.user.username}}</span>
                                                {% else %}
                                                <span style="color: #00a67c;">{{comment.user.username}}</span>
                                                {% endif %}

                                                <span> : {{reply.text}}</span>
                                                <span class="reply_r">回复</span>
                                                {% if user.is_staff %}
                                                <span class="reply_r_del" data-csrf="{{ csrf_token }}" data-reply-id="{{ reply.id }}" style="color: #7ebfff;display: none;cursor: pointer;padding: 0px 5px;">删除</span>
                                                {% endif %}
                                            </div>
                                            <div class="r_r_form col-lg-10 clearfix" style="display: none;">
                                                <form role="form" method="post" action="{%url 'comments:post_reply' post.pk %}?#comment-{{ comment.id }}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="reply_type" value="1">
                                                    <input type="hidden" name="comment" value="{{comment.id}}">
                                                    <input type="hidden" name="comment_reply" value="{{reply.id}}">
                                                    <div class="form-group">
                                                        <textarea class="form-control" rows="2" name="text"  placeholder="回复{{comment.user.username}}："></textarea>
                                                    </div>
                                                    {% for field in reply_form %}
                                                        {{ field.errors }}
                                                    {% endfor %}
                                                    <div class="form-group clearfix">
                                                        <div class="btn-group pull-right">
                                                            <button type="button" class="btn btn-default r_r_form_close">关闭</button>
                                                            <button type="submit" class="btn btn-success">发表</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                暂无评论
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock main %}

{% block toc %}
    <li class="list-group-item" style="margin-top: 10px;">
        <div class="widget widget-content">
            <h4 class="widget-title">文章目录</h4>
            {% if post.toc %}
                {{ post.toc|safe }}
            {% else %}
                <span>此文章未设目录</span>
            {% endif %}
        </div>
    </li>
{% endblock toc %}

templates/blog/message.html
{% extends 'base.html' %}

{% block middle %}
<div class="container">
    <div class="card border border-success" style="margin: 50px 0px;padding: 50px 0px; font-size: 24px;">
        <div class="card-body">欢迎您！<br>
            你可以联系我的邮箱<kbd>664374295@qq.com</kbd> <br>
        或者QQ<kbd>664374295</kbd>
        </div>

    </div>
</div>
{% endblock middle %}

templates/blog/push.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block head %}

<script>
    tinyMCE.init({
            'height': 400,
            'mode':'textareas',
            'theme':'modern',
        });
    
    $(function () {
    //    选择列表内容获取函数
        function OptionVal(select_name) {
            var str = "";
            $("#"+ select_name + " option").each(function () {
            //    遍历所有option
                var value = $(this).text();
                if ($(this).is(':checked')) {
                    str += value + " ";
                }
            });
            return str;
        }
        // alert(OptionVal())
        $("#tags").change(function () {
            var str = OptionVal('tags');
            $(this).prev().text("标签："+ str);
        });

        $("#category").change(function () {
            var str = OptionVal('category');
            $(this).prev().text("类别："+ str);
        });

        $("#add_tags_btn").click(function () {
            $(this).css("display", "none");
            $("#add_tags_form").css("display", "block");
        });

        function close_add_tags(){
            $("#add_tags_btn").css("display", "block");
            $("#add_tags_form").css("display", "none");
        }
        $("#add_tags_cancel").click(function () {
            close_add_tags();
        });

        $("#add_tags_submit").click(function () {
            if ($("#add_tags_input").val() == ""){
                alert("请输入内容后再提交！");
            } else {
                $.post("/add_tags/",
                    {
                        csrfmiddlewaretoken: $("#add_tags_input").attr("data-csrf"),
                        tags: $("#add_tags_input").val(),
                    },
                    function (data, status) {
                        var response_str = " "
                        for(var key in data['response']){
                            response_str += key + ":" + data['response'][key] + ",";
                        }
                        alert(response_str);
                        close_add_tags();
                });
            }
        });
    });
    
</script>
{% endblock head %}

{% block middle %}
<div class="container">
    <div class="row clearfix" style="padding: 50px 0px;">
        <div class="col-lg-12 col-sm-12">
            <div style="margin-bottom: 50px;">
                <form role="form" method="post" action="{% url 'blog:push' %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <input type="hidden" name="category" value="{{ category }}"/>
                    <div class="form-group">
                        <input type="text" class="form-control" id="title" name="title" placeholder="请输入文章的标题">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="excerpt" name="excerpt" placeholder="请输入文章摘要">
                        <span class="help-block">文章摘要选填！若未填系统会截取文章前一段文字！</span>
                    </div>
                    <div class="form-group">
                        <label for="body">正文</label>
                        <textarea class="form-control" id="body" name="body"></textarea>
                    </div>

                    <div class="row ">
                        <div class="col-md-5">
                            <div style="padding: 10px 0px;">标签：</div>
                            <select multiple class="form-control"  id="tags" name="tags[]">
                                {% get_tags_all as tag_list %}
                                {% for tag in tag_list %}
                                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                                {% endfor %}
                            </select>

                            <div id="add_tags_box">
                                <button type="button" class="btn-sm btn-info" id="add_tags_btn">添加标签</button>
                                <div class="form-group" id="add_tags_form" style="display: none;">
                                    <label for="add_tags_input">请输入要添加的标签，以空格隔开：</label>
                                    <input type="text" class="form-control" id="add_tags_input" name="tag_name" data-csrf="{{ csrf_token}}" placeholder="请输入需要添加的标签" >
                                    <div style="padding: 10px 0px;">
                                        <button type="button" class="btn btn-sm btn-light" id="add_tags_cancel">取消</button>
                                        <button type="button" class="btn btn-sm btn-success" id="add_tags_submit">提交</button>
                                    </div>
                                    <hr>
                                    {% get_tags_all as tag_list %}
                                    {% for tag in tag_list %}
                                        <div class="float-left" data-id="{{ tag.id }}" style="padding: 0px 10px;">{{ tag.name }}</div>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                        <div class="form-group offset-md-1 col-md-5">
                            <div style="padding: 10px 0px;">选择类别：</div>
                            <select class="form-control"  id="category" name="category">
                                {% get_categories_all as category_list %}
                                {% for category in category_list %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    {{ form.title.errors }}
                    <div class="clearfix"></div>
                    <div class="offset-5">
                        <input type="submit" class="btn-success btn-lg" value="提交">
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock middle %}