blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^python/$', views.python_list, name='python_list'),
    url(r'^linux/$', views.linux_list, name='linux_list'),
    url(r'^other/$', views.other_list, name='other_list'),
    url(r'^essay/$', views.essay_list, name='essay_list'),
    url(r'^message/$', views.message, name='message'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^push/$', views.push, name='push'),
    url(r'^add_tags/$', views.add_tags, name='add_tags'),
    url(r'^del_comment/$', views.del_comment, name='del_comment'),
    url(r'^del_reply/$', views.del_reply, name='del_reply'),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ htitle }}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu-site-verification" content="1fnRpUjRYB" />

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/highlights/github.css' %}">

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script rel="stylesheet" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script rel="stylesheet" src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
    <script rel="stylesheet" src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

    {% block head %}{% endblock head %}

    <script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>
</head>

<body style="background-color: #eee">
<!--header-->
<div id="head">
    {% if user.is_authenticated %}
    <div class="float-left">
        <img class="rounded-circle" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" style="width: 70px;height: 70px;">
    </div>
    <div class="float-right">
        <a href="{% url 'account_logout' %}?next={{ request.path }}" style="font-size: 20px;padding-right: 10px;">
            <i class="fa fa-sign-out"><span style="padding-left: 5px;">退出</span></i>
        </a>
    </div>

        {% if user.is_staff %}
        <div class="float-right">
            <a href="{% url 'blog:push' %}" style="font-size: 20px;padding-right: 10px;">
                <i class="fa fa-send "><span style="padding-left: 5px;">发文</span></i>
            </a>
        </div>
        {% endif %}

    {% else %}
    <div class="float-right">
        <a href="{% url 'account_login' %}?next={{ request.path }}" style="font-size: 20px;padding-right: 10px;">
            <i class="fa fa-user"><span style="padding-left: 5px;">登入</span></i>
        </a>
    </div>
    {% endif %}
</div>
<!--导航栏-->
<div class="clearfix">
    <nav class="navbar navbar-expand-xl bg-dark navbar-dark" role="navigation">
        <div class="container">
            <!--导航栏首页-->
            <a class="navbar-brand" href="{% url 'blog:index' %}">首页</a>
            <!--栏目-->
            <div class="collapse navbar-collapse" id="collapsibleNavbar" style="font-size: 16px;">
                <!--搜素栏目-->
                <ul class="nav navbar-nav bar">
                    <li class="nav-item Python {% if request.path == '/python/' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:python_list' %}">Python</a>
                    </li>
                    <li class="nav-item Linux {% if request.path == '/linux/' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:linux_list' %}">Linux</a>
                    </li>
                    <li class="nav-item other {% if request.path == '/other/' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:other_list' %}">PHP</a>
                    </li>
                    <li class="nav-item essay {% if request.path == '/essay/' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:essay_list' %}">随笔</a>
                    </li>
                    <li class="nav-item message {% if request.path == '/message/' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'blog:message' %}">与我联系</a>
                    </li>
                </ul>

                <form class="form-inline navbar-form navbar-right" role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                    <input class="form-control" type="search" name="q" placeholder="搜索" required/>
                    <button class="btn btn-success" type="submit">搜索</button>
                </form>
            </div>
            <button class="navbar-toggler navbar-right" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>


        </div>
    </nav>
</div>

{% block middle %}
{% endblock middle %}

<footer id="footer">
    <div style="height: 70px;">
                    <div style="width:300px;margin:0 auto; padding:20px 0;">
                <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=36073102000050" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="" style="float:left;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">赣公网安备 36073102000050号</p></a>
            </div>
         
    </div>
</footer>

</body>
</html>

templates/base_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load blog_tags %}

{% block head %}
<style>
    a:link, a:active, a:visited {
        color: #444444;
        text-decoration: none;
    }
    a:hover {
        color: red;
        text-decoration: none;
    }
</style>
    {% block head_child %}{% endblock head_child %}
{% endblock head %}

{% block middle %}
<div class="container">
    <div class="row">
        <main class="col-md-9">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-md-3">
            <ul class="list-group">
                {% block toc %}
                {% endblock toc %}
                <li class="list-group-item" style="margin: 10px 0px;">
                    <div class="widget widget-recent-posts">
                        <h4 class="widget-title">最新文章</h4>
                        {% get_recent_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                            <li>
                                <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                            </li>
                            {% empty %}
                            暂无文章！
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="widget widget-archives">
                        <h4 class="widget-title">归档</h4>
                        {% archives as date_list %}
                        <ul>
                            {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
                            </li>
                            {% empty %}
                            暂无归档！
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="widget widget-category">
                        <h4 class="widget-title">分类</h4>
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">'{{category.name}}
                                    <span class="post-count">({{ category.num_posts }})</span>
                                </a>
                            </li>
                            {% empty %}
                            暂无分类
                            {% endfor %}
                    </ul>
                </div>
                </li>
                <li class="list-group-item">
                    <div class="widget widget-tag-cloud">
                        <h4 class="widget-title">标签云</h4>
                        {% get_tags as tag_list %}
                          <ul>
                            {% for tag in tag_list %}
                            <li>
                              <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                            {% empty %}
                            暂无标签！
                            {% endfor %}
                          </ul>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </li>


            </ul>
        </aside>
    </div>
</div>
{% endblock middle %}